pipeline{
    agent any
    stages{
        stage('Dev pipeline'){
            steps{
                sh 'echo madhu'

            }
        }
        stage('SIT stage'){
            steps{
                sh 'echo uat'
            }

        }
        stage('Prod stage'){
            steps{
                sh 'echo prod'
            }
        }

    }

}